/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/BossCollectorScript")]
    [LuaRegisterType(0x18d634a2c58f4df4, typeof(LuaBehaviour))]
    public class BossCollectorScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "faa82fd0f111e4771b27a7c138b2f7f3";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_BossSound = default;
        [SerializeField] public System.Double m_Amount = 0;
        [LuaScriptPropertyAttribute("c46d9a19902b84094b4bdd7d3688878a")]
        [SerializeField] public UnityEngine.Object m_collectibleIndicator = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_BossSound),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Amount),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_collectibleIndicator),
            };
        }
    }
}

#endif
