/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/BossIndicatorUI")]
    [LuaRegisterType(0x2ebd9d4ca2a7754b, typeof(LuaBehaviour))]
    public class BossIndicatorUI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8c15d6d2c97a3ec4f8131da582896d14";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture m_BossIndicatorImage01 = default;
        [SerializeField] public UnityEngine.Texture m_BossIndicatorImage02 = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_BossIndicatorImage01),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_BossIndicatorImage02),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
            };
        }
    }
}

#endif
