/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CoinsSpawner")]
    [LuaRegisterType(0xf1fc2718501447d7, typeof(LuaBehaviour))]
    public class CoinsSpawner : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a3294022af59651428cd614340d2556a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.Transform> m_Coins = default;
        [SerializeField] public UnityEngine.GameObject m_CoinPrefab = default;
        [SerializeField] public System.Double m_SpawnDelay = 10;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Coins),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_CoinPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_SpawnDelay),
            };
        }
    }
}

#endif
