/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CollectibleIndicator")]
    [LuaRegisterType(0xd625c0eb4260ff6e, typeof(LuaBehaviour))]
    public class CollectibleIndicator : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c46d9a19902b84094b4bdd7d3688878a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_collectibleCount = 2;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_collectibleMeshes = default;
        [SerializeField] public System.Double m_intervalLength = 10;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_collectibleCount),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_collectibleMeshes),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_intervalLength),
            };
        }
    }
}

#endif
