/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CollectableScript")]
    [LuaRegisterType(0xf041cfff8a793dfe, typeof(LuaBehaviour))]
    public class CollectableScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f82526c7b87d942c090a46aefa501fb5";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_CoinSound = default;
        [SerializeField] public System.Double m_Amount = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_CoinSound),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Amount),
            };
        }
    }
}

#endif
