/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DEPRICATEDDuckCollectorScript")]
    [LuaRegisterType(0x31096b59b5d93fa7, typeof(LuaBehaviour))]
    public class DEPRICATEDDuckCollectorScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "3f3481087535f4c24b94d01be7d5fe00";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_CoinSound = default;
        [SerializeField] public System.Double m_Amount = 1;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_CoinSound),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Amount),
            };
        }
    }
}

#endif
