/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DEPRICATEDPlayerManager")]
    [LuaRegisterType(0x76301189a6ea5004, typeof(LuaBehaviour))]
    public class DEPRICATEDPlayerManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "ec9694b8f6c8f45ce90d18761ce11a54";
        public override string ScriptGUID => s_scriptGUID;


        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
            };
        }
    }
}

#endif
