/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DestroyScript")]
    [LuaRegisterType(0xbd702777d419adea, typeof(LuaBehaviour))]
    public class DestroyScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "13f500ea040dc4801bd9e633234ef01e";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_lifetime = 10;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_lifetime),
            };
        }
    }
}

#endif
