/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/IndicatorSpawner")]
    [LuaRegisterType(0xd625c0eb4260ff6e, typeof(LuaBehaviour))]
    public class IndicatorSpawner : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c46d9a19902b84094b4bdd7d3688878a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_duckPrefab = default;
        [SerializeField] public UnityEngine.GameObject m_rocketPrefab = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_duckPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_rocketPrefab),
            };
        }
    }
}

#endif
